module.exports = {
	details: 'Engine failure at 33 seconds and loss of vehicle',
	flight_number: 1,
	is_tentative: false,
	launch_date_local: '2006-03-25T10:30:00+12:00',
	launch_date_unix: 1143239400,
	launch_date_utc: '2006-03-24T22:30:00.000Z',
	launch_site: {
		site_id: 'kwajalein_atoll',
		site_name: 'Kwajalein Atoll',
		site_name_long: 'Kwajalein Atoll Omelek Island',
	},
	launch_success: false,
	launch_year: '2006',
	links: {
		article_link:
			'https://www.space.com/2196-spacex-inaugural-falcon-1-rocket-lost-launch.html',
		mission_patch: 'https://images2.imgbox.com/40/e3/GypSkayF_o.png',
		mission_patch_small: 'https://images2.imgbox.com/3c/0e/T8iJcSN3_o.png',
		video_link: 'https://www.youtube.com/watch?v=0a_00nJ_Y88',
		wikipedia: 'https://en.wikipedia.org/wiki/DemoSat',
	},
	mission_name: 'FalconSat',
	reuse: {
		capsule: false,
		core: false,
		fairings: false,
		side_core1: false,
		side_core2: false,
	},
	rocket: {
		fairings: {
			recovered: false,
			recovery_attempt: false,
			reused: false,
			ship: null,
		},
		first_stage: {
			cores: [
				{
					block: null,
					core_serial: 'Merlin1A',
					flight: 1,
					land_success: false,
					landing_type: null,
					landing_vehicle: null,
					reused: false,
				},
			],
		},
		rocket_id: 'falcon1',
		rocket_name: 'Falcon 1',
		rocket_type: 'Merlin A',
		second_stage: {
			block: 1,
			payloads: [
				{
					customers: ['DARPA'],
					manufacturer: 'SSTL',
					nationality: 'United States',
					norad_id: [],
					orbit: 'LEO',
					orbit_params: {
						apoapsis_km: 500,
						eccentricity: null,
						epoch: null,
						inclination_deg: 39,
						lifespan_years: null,
						longitude: null,
						mean_motion: null,
						periapsis_km: 400,
						period_min: null,
						raan: null,
						reference_system: 'geocentric',
						regime: 'low-earth',
						semi_major_axis_km: null,
					},
					payload_id: 'FalconSAT-2',
					payload_mass_kg: 20,
					payload_mass_lbs: 43,
					payload_type: 'Satellite',
					reused: false,
				},
			],
		},
	},
	ships: [],
	static_fire_date_utc: '2006-03-17T00:00:00.000Z',
	telemetry: {
		flight_club: null,
	},
	tentative_max_precision: 'hour',
	upcoming: false,
	ship_stats: {
		total_weight: 123456,
		oldest_ship: 'American Champion',
	},
}
